import { STRUCTURED_INTERACTION_CSS, STRUCTURED_INTERACTION_JS } from './dashboard-interactions.ts'

/** 无构建依赖的服务端 Agent 工作台；认证令牌只保留在当前页面内存。 */
export const WEB_DASHBOARD_HTML = `<!doctype html>
<html lang="zh-CN"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<title>Proma · Agent Console</title>
<style>
:root{--ink:#e7e3d6;--muted:#9b9a91;--paper:#151817;--panel:#202420;--line:#3b403b;--acid:#d7ff5f;--orange:#ff875f}*{box-sizing:border-box}body{margin:0;background:radial-gradient(circle at 80% 0,#2a3527 0,transparent 35%),var(--paper);color:var(--ink);font:15px Georgia,"Noto Serif SC",serif}.shell{display:grid;grid-template-columns:230px 1fr;min-height:100vh}aside{padding:28px 20px;border-right:1px solid var(--line)}.mark{font:700 28px/1 ui-monospace,monospace;letter-spacing:-2px}.mark i{color:var(--acid);font-style:normal}nav{margin-top:54px;display:grid;gap:5px}nav button{background:transparent;color:var(--muted);border:0;text-align:left;padding:10px;border-radius:5px;font:inherit;cursor:pointer}nav button.active,nav button:hover{background:#30352f;color:var(--acid)}main{padding:28px;max-width:1240px;width:100%;margin:auto}.top{display:flex;gap:12px;align-items:center;justify-content:space-between}.eyebrow{color:var(--acid);font:12px ui-monospace,monospace;letter-spacing:1px}.token{width:320px;background:#101210;border:1px solid var(--line);padding:9px;color:var(--ink);border-radius:5px}.grid{display:grid;grid-template-columns:280px 1fr 300px;gap:16px;margin-top:24px}.card{background:#202420;border:1px solid var(--line);border-radius:9px;padding:16px;box-shadow:0 12px 35px #0003}.card h2{font-size:13px;text-transform:uppercase;letter-spacing:1px;margin:0 0 14px;color:var(--muted)}input,textarea{width:100%;margin:5px 0;padding:10px;background:#111411;color:var(--ink);border:1px solid var(--line);border-radius:4px;font:inherit}button.action,.pending button{background:var(--acid);color:#13200c;border:0;padding:9px 12px;border-radius:4px;font-weight:bold;cursor:pointer}.list{display:grid;gap:6px;max-height:520px;overflow:auto}.item{padding:10px;border-left:2px solid var(--line);background:#171b17;cursor:pointer}.item:hover{border-color:var(--acid)}.stream{min-height:410px;max-height:62vh;overflow:auto;white-space:pre-wrap;line-height:1.65;background:#111411;padding:14px;border-radius:5px;border:1px solid var(--line)}.pending{border-left:3px solid var(--orange);padding:10px;background:#27221b;margin:8px 0}.muted{color:var(--muted);font-size:12px}@media(max-width:900px){.shell{grid-template-columns:1fr}aside{display:none}.grid{grid-template-columns:1fr}.token{width:100%}}.mini{background:#30352f;color:var(--acid);border:0;padding:4px 8px;border-radius:4px;font:inherit;cursor:pointer;margin-right:4px}.mini:hover{background:#3b403b}
${STRUCTURED_INTERACTION_CSS}</style>
<div class="shell"><aside><div class="mark">pro<i>ma</i></div><div class="muted" style="margin-top:8px">AGENT OPERATIONS</div><nav><button class="active">工作台</button><button onclick="loadView('/agent/metrics')">运行指标</button><button onclick="loadView('/agent/audit')">审计记录</button><button onclick="loadView('/agent/recovery/stale-tasks')">恢复诊断</button><button onclick="loadRuns()">运行档案</button><button onclick="loadSignals()">Signals</button><button onclick="loadDatasets()">评估数据集</button><button onclick="loadHealth()">健康度</button><button onclick="loadRegistry()">Agent 注册</button></nav></aside><main><div class="top"><div><div class="eyebrow">LIVE / SERVER RUNTIME</div><h1>Agent 工作台</h1></div><input id="token" class="token" type="password" placeholder="OIDC Bearer token（仅本页内存）" style="display:none"><span id="authModeNote" class="muted" style="display:none"></span></div><div class="grid"><section class="card"><h2>会话</h2><div id="sessions" class="list"></div><hr><input id="session" placeholder="sessionId（可选）"><input id="workspace" placeholder="workspaceSlug"><input id="channel" placeholder="channelId"><button class="action" onclick="createSession()">创建会话</button></section><section class="card"><h2 id="streamTitle">运行流</h2><div id="stream" class="stream">选择或创建会话后开始执行。</div><textarea id="prompt" rows="4" placeholder="描述要完成的工作…"></textarea><button class="action" onclick="run()">运行 Agent</button></section><section class="card"><h2>交互收件箱</h2><div id="interactions" class="list"></div><h2 style="margin-top:26px">任务</h2><div id="tasks" class="list"></div></section></div></main></div>
<script>
let selected='',streamController,lastEventId='',streamText='';const $=s=>document.querySelector(s),stream=$('#stream');const headers=()=>{const t=$('#token').value.trim();return t?{authorization:'Bearer '+t,'content-type':'application/json'}:{'content-type':'application/json'}};
async function api(path,opt={}){const r=await fetch(path,{...opt,headers:{...headers(),...(opt.headers||{})}});const text=await r.text();if(!r.ok)throw Error(text);return text}
const escape=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function show(value){stream.textContent=typeof value==='string'?value:JSON.stringify(value,null,2)}
async function refresh(){try{const [s,i,t]=await Promise.all([api('/agent/sessions'),api('/agent/interactions'),api('/agent/tasks')]);renderSessions(JSON.parse(s).sessions);renderInteractions(JSON.parse(i).interactions);renderTasks(JSON.parse(t).tasks)}catch(e){show(String(e))}}
function renderSessions(items){var html=items.filter(function(x){return !x.archived}).map(function(x){var sid=JSON.stringify(x.sessionId).replaceAll('"','&quot;');return '<div class="item" onclick="pick('+sid+')">'+escape(x.title)+'<br><span class="muted">'+escape(x.sessionId)+' · '+escape(x.modelId||'')+'</span><div style="margin-top:6px"><button class="mini" data-session-id="'+sid+'" data-op="rename" onclick="event.stopPropagation();sessOp(this)">改名</button> <button class="mini" data-session-id="'+sid+'" data-op="archive" onclick="event.stopPropagation();sessOp(this)">归档</button> <button class="mini" data-session-id="'+sid+'" data-op="cancel" onclick="event.stopPropagation();sessOp(this)">取消</button></div></div>'});return html.join('')||'<span class="muted">暂无会话</span>';}function sessOp(btn){var id=btn.dataset.sessionId;var op=btn.dataset.op;if(op==='rename'){renameSession(id)}else if(op==='archive'){archiveSession(id)}else if(op==='cancel'){cancelSession(id)}}
function taskLabel(x){return '<div class="item">'+(x.parent_task_id?'<span style="color:var(--orange)">[子]</span> ':'')+escape(x.status)+'<br><span class="muted">'+escape(x.task_id)+(x.parent_task_id?' · parent '+escape(x.parent_task_id):'')+'</span></div>'}function renderTasks(items){$('#tasks').innerHTML=items.map(x=>taskLabel(x)).join('')||'<span class="muted">暂无任务</span>'}
function renderInteractions(items){$('#interactions').innerHTML=items.filter(x=>x.status==='pending').map(x=>renderInteractionCard(x)).join('')||'<span class="muted">没有待处理交互</span>'}

function renderInteractionCard(x){const requestId=JSON.stringify(x.requestId).replaceAll('"','&quot;');const version=x.version||1;switch(x.kind){case'permission':return renderPermissionCard(x.request,requestId,version);case'ask_user':return renderAskUserCard(x.request,requestId,version);case'plan':return renderPlanCard(x.request,requestId,version);case'goal':case'mcp_oauth':case'external_action':return renderActionCard(x,requestId,version);default:return renderFallbackCard(x,requestId,version)}}

function renderPermissionCard(req,requestId,version){const riskColor=req.dangerLevel==='high'?'var(--orange)':req.dangerLevel==='medium'?'#ffcc00':'var(--acid)';const riskLabel=req.dangerLevel==='high'?'高风险':req.dangerLevel==='medium'?'中风险':'低风险';const toolInputPreview=JSON.stringify(req.toolInput,null,2).slice(0,500);return'<div class="pending interaction-card" data-request-id="'+es(requestId)+'" data-kind="permission" data-version="'+version+'"><div class="interaction-header"><span class="interaction-badge" style="background:'+riskColor+'">'+riskLabel+'</span><b>权限请求</b> · '+es(req.toolName)+'</div><div class="interaction-body">'+(req.sdkTitle?'<div class="sdk-title">'+es(req.sdkTitle)+'</div>':'')+(req.sdkDescription?'<div class="sdk-desc">'+es(req.sdkDescription)+'</div>':'')+(req.description?'<div class="description">'+es(req.description)+'</div>':'')+(req.command?'<div class="command-box"><code>'+es(req.command)+'</code></div>':'')+'<details class="tool-input-details"><summary>工具输入参数</summary><pre class="tool-input">'+es(toolInputPreview)+(JSON.stringify(req.toolInput).length>500?'...':'')+'</pre></details>'+(req.decisionReason?'<div class="reason">理由: '+es(req.decisionReason)+'</div>':'')+'</div><div class="interaction-actions"><label class="checkbox-label"><input type="checkbox" data-always-allow> 本次会话始终允许此工具</label><div class="button-row"><button class="action-btn approve" onclick="respondPermission(\''+requestId+'\',true,this)">✓ 批准一次</button><button class="action-btn deny" onclick="respondPermission(\''+requestId+'\',false,this)">✗ 拒绝</button></div></div></div>'}

function renderAskUserCard(req,requestId,version){const isTakeover=req.kind==='computer_use_takeover';const title=isTakeover?'🖥️ Computer Use 接管请求':'用户问答';const questionsHtml=(req.questions||[]).map((q,i)=>renderQuestion(q,i)).join('');return'<div class="pending interaction-card '+(isTakeover?'takeover-header':'')+'" data-request-id="'+es(requestId)+'" data-kind="ask_user" data-version="'+version+'"><div class="interaction-header"><b>'+title+'</b>'+(isTakeover?'<span class="warning-badge">需要人工介入</span>':'')+'</div><div class="interaction-body askuser-form">'+questionsHtml+'</div><div class="interaction-actions"><button class="action-btn approve" onclick="respondAskUser(\''+requestId+'\',this)">✓ 提交回答</button></div></div>'}

function renderQuestion(q,index){const header=q.header?'<span class="question-header">'+es(q.header)+'</span>':'';if(q.options&&q.options.length>0){if(q.multiSelect){const opts=q.options.map((opt,oi)=>'<label class="option-item"><input type="checkbox" value="'+es(opt.label)+'" data-answer="'+es(q.question)+'" data-multiselect="true"><span class="option-label">'+es(opt.label)+'</span>'+(opt.description?'<span class="option-desc">'+es(opt.description)+'</span>':'')+'</label>').join('');return'<div class="question-block" data-question="'+es(q.question)+'">'+header+'<label class="question-label">'+es(q.question)+'</label><div class="options-grid">'+opts+'</div></div>'}else{const opts=q.options.map((opt,oi)=>'<label class="option-item"><input type="radio" name="'+es(q.question)+'" value="'+es(opt.label)+'" data-answer="'+es(q.question)+'"><span class="option-label">'+es(opt.label)+'</span>'+(opt.description?'<span class="option-desc">'+es(opt.description)+'</span>':'')+'</label>').join('');return'<div class="question-block" data-question="'+es(q.question)+'">'+header+'<label class="question-label">'+es(q.question)+'</label><div class="options-grid">'+opts+'</div></div>'}}return'<div class="question-block" data-question="'+es(q.question)+'">'+header+'<label class="question-label">'+es(q.question)+'</label><input type="text" class="question-input" data-answer="'+es(q.question)+'" placeholder="请输入回答…"></div>'}

function renderPlanCard(req,requestId,version){const planContent=req.toolInput?.plan||req.toolInput?.description||'未提供计划内容';const promptsHtml=(req.allowedPrompts||[]).map(p=>'<div class="allowed-prompt-item"><span class="prompt-tool">'+es(p.tool)+'</span><span class="prompt-text">'+es(p.prompt)+'</span></div>').join('');return'<div class="pending interaction-card plan-card" data-request-id="'+es(requestId)+'" data-kind="plan" data-version="'+version+'"><div class="interaction-header"><span class="interaction-badge" style="background:#6b8cff">计划审批</span><b>ExitPlanMode</b></div><div class="interaction-body"><div class="plan-content"><h4>计划内容</h4><pre class="plan-text">'+es(String(planContent))+'</pre></div>'+(promptsHtml?'<div class="allowed-prompts"><h4>批准后将执行的 Prompts</h4>'+promptsHtml+'</div>':'')+'<div class="feedback-area"><label>反馈 / 修改要求（可选）</label><textarea data-feedback rows="3" placeholder="如需调整计划，请在此输入反馈…"></textarea></div></div><div class="interaction-actions plan-actions"><button class="action-btn approve-auto" onclick="respondPlan(\''+requestId+'\',\'approve_auto\',this)">✓ 批准自动执行</button><button class="action-btn approve-edit" onclick="respondPlan(\''+requestId+'\',\'approve_edit\',this)">✓ 批准并切换编辑模式</button><button class="action-btn feedback" onclick="respondPlan(\''+requestId+'\',\'feedback\',this)">💬 要求调整</button><button class="action-btn deny" onclick="respondPlan(\''+requestId+'\',\'deny\',this)">✗ 拒绝</button></div></div>'}

function renderActionCard(record,requestId,version){const req=record.request||{};const actions=(req.actions||[]);const actionsHtml=actions.map(action=>'<button class="action-btn action-choice" onclick="respondAction(\''+requestId+'\',\''+es(action)+'\',this)">'+es(action)+'</button>').join('');const kindLabel=record.kind==='goal'?'目标检查点':record.kind==='mcp_oauth'?'MCP OAuth 授权':'外部操作';return'<div class="pending interaction-card" data-request-id="'+es(requestId)+'" data-kind="'+record.kind+'" data-version="'+version+'"><div class="interaction-header"><span class="interaction-badge" style="background:#a855f7">'+kindLabel+'</span><b>'+es(req.title||record.kind)+'</b></div><div class="interaction-body">'+(req.description?'<div class="description">'+es(req.description)+'</div>':'')+(req.detail?'<details><summary>详情</summary><pre>'+es(JSON.stringify(req.detail,null,2))+'</pre></details>':'')+'</div><div class="interaction-actions action-choices">'+(actionsHtml||'<span class="muted">无可选动作</span>')+'</div></div>'}

function renderFallbackCard(record,requestId,version){return'<div class="pending interaction-card" data-request-id="'+es(requestId)+'" data-kind="'+record.kind+'" data-version="'+version+'"><div class="interaction-header"><b>'+es(record.kind)+'</b></div><div class="interaction-body"><pre class="muted">'+es(JSON.stringify(record.request,null,2))+'</pre></div><div class="interaction-actions"><button class="action-btn" onclick="respondFallback(\''+requestId+'\',this)">确认</button></div></div>'}

function es(s){return escape(s==null?'':String(s))}
function pick(id){if(selected!==id){lastEventId='';streamText=''}selected=id;$('#session').value=id;$('#streamTitle').textContent='运行流 · '+id;subscribe()}
async function createSession(){try{const r=await api('/agent/sessions',{method:'POST',body:JSON.stringify({sessionId:$('#session').value||undefined,workspaceSlug:$('#workspace').value,channelId:$('#channel').value})});pick(JSON.parse(r).session.sessionId);refresh()}catch(e){show(String(e))}}
async function run(){const id=selected||$('#session').value;if(!id)return show('请先选择会话');try{streamText='';show('任务已提交，等待流式事件…');await api('/agent/sessions/'+encodeURIComponent(id)+'/run',{method:'POST',body:JSON.stringify({prompt:$('#prompt').value})});subscribe();refresh()}catch(e){show(String(e))}}
function subscribe(){streamController?.abort();const id=selected||$('#session').value;if(!id)return;streamController=new AbortController();consumeEvents(id,streamController.signal).catch(e=>{if(e.name!=='AbortError')show(String(e))})}
async function consumeEvents(id,signal){const r=await fetch('/agent/sessions/'+encodeURIComponent(id)+'/events'+(lastEventId?'?afterId='+encodeURIComponent(lastEventId):''),{headers:headers(),signal});if(!r.ok||!r.body)throw Error(await r.text());const reader=r.body.getReader(),decoder=new TextDecoder();let buffer='';while(!signal.aborted){const next=await reader.read();if(next.done)break;buffer+=decoder.decode(next.value,{stream:true});const parts=buffer.split('\n\n');buffer=parts.pop()||'';for(const part of parts)applyEnvelope(part)}if(!signal.aborted)setTimeout(()=>subscribe(),500)}
function applyEnvelope(raw){const id=raw.match(/^id: (.+)$/m)?.[1];const data=raw.match(/^data: (.+)$/m)?.[1];if(id)lastEventId=id;if(!data)return;const envelope=JSON.parse(data),p=envelope.payload;if(p.kind!=='agent_event')return;const e=p.event;if(e.type==='text_delta')streamText+=e.text;else if(e.type==='tool_start')streamText+='\\n[工具] '+e.toolName+'\\n';else if(e.type==='tool_result')streamText+='[结果] '+e.result+'\\n';else if(e.type==='error')streamText+='\\n[错误] '+e.message+'\\n';else if(e.type==='complete')streamText+='\\n[完成]\\n';stream.textContent=streamText;stream.scrollTop=stream.scrollHeight}
async function loadView(path){try{show(JSON.parse(await api(path)))}catch(e){show(String(e))}}

// ===== 新增可视化视图：运行档案 / Signals / 评估数据集 =====
function setTab(name){document.querySelectorAll('nav button').forEach(b=>b.classList.toggle('active',b.textContent.trim()===name))}
function viz(html){let v=document.getElementById('viz');if(!v){v=document.createElement('section');v.id='viz';v.style.cssText='margin-top:24px';document.querySelector('main').appendChild(v)}v.innerHTML=html;return v}
function es(s){return escape(s==null?'':String(s))}
function spanTree(spans,depth){const ul=(ary,d)=>{return '<div class="list" style="max-height:70vh">'+ary.map(s=>{const dur=s.endedAt>=s.startedAt?(s.endedAt-s.startedAt):0;const m=s.meta||{};const cost=m.costMicroUsd!=null?' · $'+(m.costMicroUsd/1e6).toFixed(4):'';const tok=m.inputTokens!=null?' · '+(m.inputTokens||0)+'→'+(m.outputTokens||0)+'tok':'';const badge=s.status==='error'?'<span style="color:var(--orange)">✗</span>':'<span style="color:var(--acid)">✓</span>';const kids=s.children&&s.children.length?ul(s.children,d+1):'';return '<div style="border-left:'+(d?2:3)+'px solid '+(s.status==='error'?'var(--orange)':'var(--line)')+';padding:4px 10px;margin:2px 0;background:#171b17">'+badge+' <b>'+es(s.name)+'</b><span class="muted"> '+dur+'ms'+tok+cost+'</span>'+(s.error?'<div class="muted" style="color:var(--orange)">'+es(s.error)+'</div>':'')+kids+'</div>'}).join('')+'</div>'};return ul(spans||[],depth)}

// —— 运行档案 ——
function taskCard(x){const kids=(x.children&&x.children.length)?'<div style="margin-left:18px;border-left:2px solid var(--line);padding-left:8px">'+x.children.map(c=>taskCard(c)).join('')+'</div>':'';return '<div style="margin:3px 0;padding:6px;background:#171b17;border-left:3px solid '+(x.status==='error'?'var(--orange)':'var(--acid)')+'"><button class="action" style="width:100%;text-align:left;margin:0" onclick="loadRun(\''+es(x.task_id)+'\')">'+(x.children&&x.children.length?'<span style="color:var(--orange)">[父+'+x.children.length+']</span> ':'')+es(x.status)+' · '+es(x.task_id)+'<br><span class="muted">'+es(x.started_at)+'</span></button>'+kids+'</div>'}async function loadRuns(){setTab('运行档案');try{const t=JSON.parse(await api('/agent/tasks'));const tasks=t.tasks||[];const byId=new Map(tasks.map(x=>[x.task_id,x]));tasks.forEach(x=>{x.children=[]});const roots=[];tasks.forEach(x=>{const p=byId.get(x.parent_task_id);if(p)p.children.push(x);else roots.push(x)});const list=roots.map(x=>taskCard(x)).join('')||'<span class="muted">暂无任务</span>';viz('<div class="card"><h2>运行档案（按父子展开，点击加载 span 树）</h2><div class="list" style="max-height:70vh">'+list+'</div></div>')}catch(e){viz('<div class="card"><h2>运行档案</h2>'+es(e)+'</div>')}}
async function loadRun(id){try{const p=JSON.parse(await api('/agent/runs/'+encodeURIComponent(id)));let html='<div class="card"><h2>运行档案 · '+es(id)+'</h2>';if(p.usage)html+='<span class="muted">tokens '+es(p.usage.inputTokens||0)+'→'+es(p.usage.outputTokens||0)+' · cost $'+(p.usage.costMicroUsd||0)/1e6+'</span>';html+='<br><span class="muted">audit '+es(p.audit.length)+' 条</span>'+p.audit.map(a=>'<div class="muted">'+es(a.result)+' · '+es(a.action)+'</div>').join('')+'</div><div class="card"><h2>span 树（latency · token · cost）</h2>'+spanTree(p.trace,0)+'</div>';viz(html)}catch(e){viz('<div class="card"><h2>运行档案</h2>'+es(e)+'</div>')}}

// —— Signals ——
async function loadSignals(){setTab('Signals');try{const [s,h]=await Promise.all([api('/agent/signals'),api('/agent/signals/hits')]);const signals=JSON.parse(s).signals;const hits=JSON.parse(h).hits;let html='<div class="card"><h2>新建 Signal（自然语言描述）+ matcher</h2><input id="sigDesc" placeholder="人话描述，如：如果 agent 卡在循环里提醒我"><div class="muted">工具连续失败（循环检测）— 工具前缀 tool:Bash</div><input id="sigTool" value="tool:Bash" placeholder="namePrefix"><input id="sigFail" value="3" type="number"><button class="action" onclick="createSignal()">创建</button></div>';html+='<div class="card"><h2>Signals</h2><div class="list">'+signals.map(x=>'<div class="item">'+es(x.description)+'<div class="muted">'+es(x.matcher.type)+' · hits '+es(x.hitCount)+' · '+(x.enabled?'enabled':'off')+'</div></div>').join('')+'</div></div>';html+='<div class="card"><h2>命中记录</h2><div class="list">'+hits.map(x=>'<div class="item">'+es(x.message)+'<div class="muted">'+es(x.createdAt)+'</div></div>').join('')+'</div></div>';viz(html)}catch(e){viz('<div class="card"><h2>Signals</h2>'+es(e)+'</div>')}}
async function createSignal(){try{const body=JSON.stringify({description:$('#sigDesc').value||'未命名 Signal',matcher:{type:'tool_repeat_failure',namePrefix:$('#sigTool').value||'tool:',minFailures:Number($('#sigFail').value)||3,windowMs:600000},enabled:true});await api('/agent/signals',{method:'POST',body});loadSignals()}catch(e){viz('<div class="card"><h2>Signals</h2>'+es(e)+'</div>')}}

// —— 评估数据集 ——
async function loadDatasets(){setTab('评估数据集');try{const s=JSON.parse(await api('/agent/datasets'));const list=s.datasets.map(x=>'<button class="action" style="width:100%;text-align:left;margin:3px 0" onclick="loadSamples(\''+es(x.datasetId)+'\')">'+es(x.name)+' · '+es(x.count)+' samples<br><span class="muted">'+es(x.createdAt)+'</span></button>').join('')||'<span class="muted">暂无数据集</span>';let html='<div class="card"><h2>新建评估数据集（从运行窗口采样）</h2><input id="dsName" placeholder="名称"><input id="dsWindow" value="3600000" type="number"><span class="muted"> ms 窗口</span><button class="action" onclick="createDataset()">采样创建</button></div>';html+='<div class="card"><h2>数据集（点击查看样本）</h2><div class="list">'+list+'</div></div>';viz(html)}catch(e){viz('<div class="card"><h2>评估数据集</h2>'+es(e)+'</div>')}}
async function createDataset(){try{const body=JSON.stringify({name:$('#dsName').value||'采样集',windowMs:Number($('#dsWindow').value)||3600000,sampleRate:1});await api('/agent/datasets',{method:'POST',body});loadDatasets()}catch(e){viz('<div class="card"><h2>评估数据集</h2>'+es(e)+'</div>')}}
async function loadSamples(id){try{const s=JSON.parse(await api('/agent/datasets/'+encodeURIComponent(id)+'/samples'));const list=s.samples.map(x=>'<div class="item"><b>'+es(x.status)+'</b> '+es(x.name)+'<div class="muted">'+es(x.taskId)+' · '+es(x.durationMs)+'ms'+(x.costMicroUsd!=null?' · $'+(x.costMicroUsd/1e6).toFixed(4):'')+'</div>'+(x.input?'<div class="muted">in: '+es(x.input)+'</div>':'')+(x.output?'<div class="muted">out: '+es(x.output)+'</div>':'')+(x.error?'<div class="muted" style="color:var(--orange)">'+es(x.error)+'</div>':'')+'</div>').join('')||'<span class="muted">暂无样本</span>';viz('<div class="card"><h2>数据集样本 · '+es(id)+'</h2><div class="list">'+list+'</div></div>')}catch(e){viz('<div class="card"><h2>数据集</h2>'+es(e)+'</div>')}}
async function loadHealth(){setTab('健康度');try{const h=JSON.parse(await api('/agent/health')).health;const g=x=>x==='good'?'#d7ff5f':x==='warn'?'#ff875f':'#ff5f5f';let html='<div class="card"><h2>健康度 - 贵慢重准</h2><div style="display:grid;grid-template-columns:1fr 1fr;gap:12px">'+'<div><b style="color:'+g(h.latency.grade)+'">慢 '+h.latency.p95Ms+'ms</b><span class="muted"> target '+h.latency.targetMs+'ms</span></div>'+'<div><b style="color:'+g(h.accuracy.grade)+'">准 '+(h.accuracy.successRate*100).toFixed(1)+'%</b><span class="muted"> 成功率</span></div>'+'<div><b>贵 $'+(h.cost.monthlyMicroUsd/1e6).toFixed(2)+'</b><span class="muted"> 本月</span></div>'+'<div><b>重 '+h.volume.totalRuns+' runs / '+(h.volume.totalTokens/1e3).toFixed(1)+'k tokens</b></div></div>';if(h.budget.monthlyLimitMicroUsd!=null)html+='<div style="margin-top:12px"><span class="muted">预算已用 </span><b>'+h.budget.usedPercent+'%</b><div style="background:#3b403b;height:8px;border-radius:4px;margin-top:4px"><div style="background:'+(h.budget.usedPercent>=80?'#ff875f':'#d7ff5f')+';height:8px;border-radius:4px;width:'+Math.min(h.budget.usedPercent,100)+'%"></div></div></div>';viz(html)}catch(e){viz('<div class="card"><h2>健康度</h2>'+es(e)+'</div>')}}
async function loadRegistry(){setTab('Agent 注册');try{const r=JSON.parse(await api('/agent/registry'));const cards=r.cards||[];const list=cards.map(c=>'<div class="item"><b>'+es(c.name)+'</b> '+es(c.role)+'<br><span class="muted">'+es(c.cardId)+' '+es(c.source)+' caps:'+es(c.capabilities&&c.capabilities.length?c.capabilities.join(','):'')+'</span></div>').join('')||'<span class="muted">暂无 Agent 注册</span>';viz('<div class="card"><h2>Agent 注册表 ('+cards.length+')</h2><div class="list">'+list+'</div></div>')}catch(e){viz('<div class="card"><h2>Agent 注册</h2>'+es(e)+'</div>')}}
async function renameSession(id){const t=prompt('新标题：');if(!t)return;try{await api('/agent/sessions/'+encodeURIComponent(id),{method:'PATCH',body:JSON.stringify({title:t})});refresh()}catch(e){show(String(e))}}
async function archiveSession(id){try{await api('/agent/sessions/'+encodeURIComponent(id),{method:'PATCH',body:JSON.stringify({archived:true})});refresh()}catch(e){show(String(e))}}
async function cancelSession(id){if(!confirm('取消该会话的进行中任务？'))return;try{await api('/agent/sessions/'+encodeURIComponent(id),{method:'DELETE'});show('已触发取消');refresh()}catch(e){show(String(e))}}
async function applyAuthMode(){try{const s=JSON.parse(await api('/auth/status'));const m=s.authMode;const localMode=(m==='local'||m==='none');const tok=$('#token'),note=$('#authModeNote');if(localMode){tok.style.display='none';note.style.display='inline';note.textContent='本地凭据登录，无需 Bearer token'+(m==='none'?'（API 需配置 OIDC 或会话）':'，API 用会话 cookie');document.querySelector('.top h1').style.display='inline'}else{tok.style.display='';note.style.display='none'}}catch(e){/* 忽略：默认保留 token 输入 */}}
applyAuthMode();refresh();setInterval(refresh,5000)
${STRUCTURED_INTERACTION_JS}
</script></html>`
