/** 无构建依赖的服务端 Agent 工作台；认证令牌只保留在当前页面内存。 */
export const WEB_DASHBOARD_HTML = `<!doctype html>
<html lang="zh-CN"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<title>Proma · Agent Console</title>
<style>
:root{--ink:#e7e3d6;--muted:#9b9a91;--paper:#151817;--panel:#202420;--line:#3b403b;--acid:#d7ff5f;--orange:#ff875f}*{box-sizing:border-box}body{margin:0;background:radial-gradient(circle at 80% 0,#2a3527 0,transparent 35%),var(--paper);color:var(--ink);font:15px Georgia,"Noto Serif SC",serif}.shell{display:grid;grid-template-columns:230px 1fr;min-height:100vh}aside{padding:28px 20px;border-right:1px solid var(--line)}.mark{font:700 28px/1 ui-monospace,monospace;letter-spacing:-2px}.mark i{color:var(--acid);font-style:normal}nav{margin-top:54px;display:grid;gap:5px}nav button{background:transparent;color:var(--muted);border:0;text-align:left;padding:10px;border-radius:5px;font:inherit;cursor:pointer}nav button.active,nav button:hover{background:#30352f;color:var(--acid)}main{padding:28px;max-width:1240px;width:100%;margin:auto}.top{display:flex;gap:12px;align-items:center;justify-content:space-between}.eyebrow{color:var(--acid);font:12px ui-monospace,monospace;letter-spacing:1px}.token{width:320px;background:#101210;border:1px solid var(--line);padding:9px;color:var(--ink);border-radius:5px}.grid{display:grid;grid-template-columns:280px 1fr 300px;gap:16px;margin-top:24px}.card{background:#202420;border:1px solid var(--line);border-radius:9px;padding:16px;box-shadow:0 12px 35px #0003}.card h2{font-size:13px;text-transform:uppercase;letter-spacing:1px;margin:0 0 14px;color:var(--muted)}input,textarea{width:100%;margin:5px 0;padding:10px;background:#111411;color:var(--ink);border:1px solid var(--line);border-radius:4px;font:inherit}button.action,.pending button{background:var(--acid);color:#13200c;border:0;padding:9px 12px;border-radius:4px;font-weight:bold;cursor:pointer}.list{display:grid;gap:6px;max-height:520px;overflow:auto}.item{padding:10px;border-left:2px solid var(--line);background:#171b17;cursor:pointer}.item:hover{border-color:var(--acid)}.stream{min-height:410px;max-height:62vh;overflow:auto;white-space:pre-wrap;line-height:1.65;background:#111411;padding:14px;border-radius:5px;border:1px solid var(--line)}.pending{border-left:3px solid var(--orange);padding:10px;background:#27221b;margin:8px 0}.muted{color:var(--muted);font-size:12px}@media(max-width:900px){.shell{grid-template-columns:1fr}aside{display:none}.grid{grid-template-columns:1fr}.token{width:100%}}</style>
<div class="shell"><aside><div class="mark">pro<i>ma</i></div><div class="muted" style="margin-top:8px">AGENT OPERATIONS</div><nav><button class="active">工作台</button><button onclick="loadView('/agent/metrics')">运行指标</button><button onclick="loadView('/agent/audit')">审计记录</button><button onclick="loadView('/agent/recovery/stale-tasks')">恢复诊断</button></nav></aside><main><div class="top"><div><div class="eyebrow">LIVE / SERVER RUNTIME</div><h1>Agent 工作台</h1></div><input id="token" class="token" type="password" placeholder="OIDC Bearer token（仅本页内存）"></div><div class="grid"><section class="card"><h2>会话</h2><div id="sessions" class="list"></div><hr><input id="session" placeholder="sessionId（可选）"><input id="workspace" placeholder="workspaceSlug"><input id="channel" placeholder="channelId"><button class="action" onclick="createSession()">创建会话</button></section><section class="card"><h2 id="streamTitle">运行流</h2><div id="stream" class="stream">选择或创建会话后开始执行。</div><textarea id="prompt" rows="4" placeholder="描述要完成的工作…"></textarea><button class="action" onclick="run()">运行 Agent</button></section><section class="card"><h2>交互收件箱</h2><div id="interactions" class="list"></div><h2 style="margin-top:26px">任务</h2><div id="tasks" class="list"></div></section></div></main></div>
<script>
let selected='',streamController,lastEventId='',streamText='';const $=s=>document.querySelector(s),stream=$('#stream');const headers=()=>{const t=$('#token').value.trim();return t?{authorization:'Bearer '+t,'content-type':'application/json'}:{'content-type':'application/json'}};
async function api(path,opt={}){const r=await fetch(path,{...opt,headers:{...headers(),...(opt.headers||{})}});const text=await r.text();if(!r.ok)throw Error(text);return text}
const escape=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function show(value){stream.textContent=typeof value==='string'?value:JSON.stringify(value,null,2)}
async function refresh(){try{const [s,i,t]=await Promise.all([api('/agent/sessions'),api('/agent/interactions'),api('/agent/tasks')]);renderSessions(JSON.parse(s).sessions);renderInteractions(JSON.parse(i).interactions);renderTasks(JSON.parse(t).tasks)}catch(e){show(String(e))}}
function renderSessions(items){$('#sessions').innerHTML=items.map(x=>'<div class="item" onclick="pick('+JSON.stringify(x.sessionId).replaceAll('"','&quot;')+')">'+escape(x.title)+'<br><span class="muted">'+escape(x.sessionId)+' · '+escape(x.modelId)+'</span></div>').join('')||'<span class="muted">暂无会话</span>'}
function renderTasks(items){$('#tasks').innerHTML=items.map(x=>'<div class="item">'+escape(x.status)+'<br><span class="muted">'+escape(x.task_id)+'</span></div>').join('')||'<span class="muted">暂无任务</span>'}
function renderInteractions(items){$('#interactions').innerHTML=items.filter(x=>x.status==='pending').map(x=>{const q=x.request.questions?.map(q=>'<label>'+escape(q.question)+'<input data-answer="'+escape(q.question)+'"></label>').join('')||'';const plan=x.kind==='plan'?'<pre class="muted">'+escape(x.request.toolInput?.plan||'未提供计划内容')+'</pre><textarea data-feedback rows="2" placeholder="可选反馈 / 修改要求"></textarea>':'';const requestId=JSON.stringify(x.requestId).replaceAll('"','&quot;');const actions=x.kind==='plan'?'<br><button onclick="respond('+requestId+',true,\'approve_auto\')">批准执行</button> <button onclick="respond('+requestId+',true,\'approve_edit\')">批准并附反馈</button> <button onclick="respond('+requestId+',false,\'deny\')">拒绝</button> <button onclick="respond('+requestId+',true,\'feedback\')">要求调整</button>':'<br><button onclick="respond('+requestId+',true)">允许 / 提交</button> <button onclick="respond('+requestId+',false)">拒绝</button>';return '<div class="pending" data-request-id="'+escape(x.requestId)+'" data-kind="'+escape(x.kind)+'" data-version="'+escape(x.version)+'"><b>'+escape(x.kind)+'</b> · '+escape(x.request.toolName||'用户问题')+'<br><span class="muted">'+escape(x.request.description||'等待回答')+'</span>'+plan+q+actions+'</div>'}).join('')||'<span class="muted">没有待处理交互</span>'}
function pick(id){if(selected!==id){lastEventId='';streamText=''}selected=id;$('#session').value=id;$('#streamTitle').textContent='运行流 · '+id;subscribe()}
async function createSession(){try{const r=await api('/agent/sessions',{method:'POST',body:JSON.stringify({sessionId:$('#session').value||undefined,workspaceSlug:$('#workspace').value,channelId:$('#channel').value})});pick(JSON.parse(r).session.sessionId);refresh()}catch(e){show(String(e))}}
async function run(){const id=selected||$('#session').value;if(!id)return show('请先选择会话');try{streamText='';show('任务已提交，等待流式事件…');await api('/agent/sessions/'+encodeURIComponent(id)+'/run',{method:'POST',body:JSON.stringify({prompt:$('#prompt').value})});subscribe();refresh()}catch(e){show(String(e))}}
function subscribe(){streamController?.abort();const id=selected||$('#session').value;if(!id)return;streamController=new AbortController();consumeEvents(id,streamController.signal).catch(e=>{if(e.name!=='AbortError')show(String(e))})}
async function consumeEvents(id,signal){const r=await fetch('/agent/sessions/'+encodeURIComponent(id)+'/events'+(lastEventId?'?afterId='+encodeURIComponent(lastEventId):''),{headers:headers(),signal});if(!r.ok||!r.body)throw Error(await r.text());const reader=r.body.getReader(),decoder=new TextDecoder();let buffer='';while(!signal.aborted){const next=await reader.read();if(next.done)break;buffer+=decoder.decode(next.value,{stream:true});const parts=buffer.split('\n\n');buffer=parts.pop()||'';for(const part of parts)applyEnvelope(part)}if(!signal.aborted)setTimeout(()=>subscribe(),500)}
function applyEnvelope(raw){const id=raw.match(/^id: (.+)$/m)?.[1];const data=raw.match(/^data: (.+)$/m)?.[1];if(id)lastEventId=id;if(!data)return;const envelope=JSON.parse(data),p=envelope.payload;if(p.kind!=='agent_event')return;const e=p.event;if(e.type==='text_delta')streamText+=e.text;else if(e.type==='tool_start')streamText+='\\n[工具] '+e.toolName+'\\n';else if(e.type==='tool_result')streamText+='[结果] '+e.result+'\\n';else if(e.type==='error')streamText+='\\n[错误] '+e.message+'\\n';else if(e.type==='complete')streamText+='\\n[完成]\\n';stream.textContent=streamText;stream.scrollTop=stream.scrollHeight}
async function respond(id,ok,planAction){try{const card=[...document.querySelectorAll('.pending')].find(x=>x.dataset.requestId===id);if(!card)throw Error('交互已不在待处理列表');const answers={};card.querySelectorAll('[data-answer]').forEach(x=>answers[x.dataset.answer]=x.value);const feedback=card.querySelector('[data-feedback]')?.value;const response=card.dataset.kind==='ask_user'?{requestId:id,answers}:card.dataset.kind==='plan'?{requestId:id,action:planAction||(ok?'approve_auto':'deny'),...(feedback?{feedback}: {})}:{requestId:id,behavior:ok?'allow':'deny',alwaysAllow:false};const resolutionId=globalThis.crypto?.randomUUID?.()||('response-'+Date.now());await api('/agent/interactions/'+id+'/respond',{method:'POST',body:JSON.stringify({response,expectedVersion:Number(card.dataset.version),resolutionId})});refresh()}catch(e){show(String(e))}}
async function loadView(path){try{show(JSON.parse(await api(path)))}catch(e){show(String(e))}}refresh();setInterval(refresh,5000)
</script></html>`
