import * as React from 'react'
import type { NewMediaMetricSnapshot, NewMediaSocialReport, NewMediaTrendItem } from '@gravitas/shared'

export function InsightsPanel({ snapshots, trends, report, onRefresh }: { snapshots: NewMediaMetricSnapshot[]; trends: NewMediaTrendItem[]; report: NewMediaSocialReport | null; onRefresh: () => Promise<void> }): React.ReactElement {
  const [contentId, setContentId] = React.useState('')
  const [impressions, setImpressions] = React.useState('')
  const [engagements, setEngagements] = React.useState('')
  const [trendTitle, setTrendTitle] = React.useState('')
  const addMetric = async (): Promise<void> => { if (!contentId.trim()) return; await window.electronAPI.paa.newMedia.analytics.ingestSnapshot({ platform: 'xiaohongshu', contentId, capturedAt: Date.now(), impressions: Number(impressions) || 0, engagements: Number(engagements) || 0, followersGained: 0 }); setContentId(''); setImpressions(''); setEngagements(''); await onRefresh() }
  const addTrend = async (): Promise<void> => { if (!trendTitle.trim()) return; await window.electronAPI.paa.newMedia.analytics.ingestTrend({ title: trendTitle, summary: '人工录入热点，待进一步核验。', source: '本地人工录入', observedAt: Date.now(), heat: 50, relatedKeywords: trendTitle.split(/\s+/), risk: 'medium' }); setTrendTitle(''); await onRefresh() }
  return <div className="mx-auto max-w-6xl space-y-4"><section className="grid gap-3 md:grid-cols-4">{[['总曝光', report?.totalImpressions ?? 0], ['总互动', report?.totalEngagements ?? 0], ['互动率', `${((report?.engagementRate ?? 0) * 100).toFixed(2)}%`], ['新增粉丝', report?.followersGained ?? 0]].map(([label, value]) => <div key={label} className="rounded-2xl bg-background p-4 shadow-sm"><div className="text-xs text-foreground/50">{label}</div><div className="mt-2 text-2xl font-semibold">{value}</div></div>)}</section><div className="grid gap-4 lg:grid-cols-2"><section className="rounded-2xl bg-background p-4 shadow-sm"><h2 className="mb-3 font-medium">录入指标快照</h2><div className="space-y-2"><input value={contentId} onChange={e => setContentId(e.target.value)} placeholder="内容标识" className="w-full rounded-lg bg-muted px-3 py-2 text-sm"/><div className="grid grid-cols-2 gap-2"><input value={impressions} onChange={e => setImpressions(e.target.value)} placeholder="曝光量" className="rounded-lg bg-muted px-3 py-2 text-sm"/><input value={engagements} onChange={e => setEngagements(e.target.value)} placeholder="互动量" className="rounded-lg bg-muted px-3 py-2 text-sm"/></div><button onClick={() => void addMetric()} className="rounded-lg bg-primary px-3 py-2 text-sm text-primary-foreground">保存快照</button></div><div className="mt-4 text-xs text-foreground/45">已保存 {snapshots.length} 条本地快照</div></section><section className="rounded-2xl bg-background p-4 shadow-sm"><h2 className="mb-3 font-medium">热点雷达</h2><div className="flex gap-2"><input value={trendTitle} onChange={e => setTrendTitle(e.target.value)} placeholder="手工录入热点标题" className="flex-1 rounded-lg bg-muted px-3 py-2 text-sm"/><button onClick={() => void addTrend()} className="rounded-lg bg-primary px-3 py-2 text-sm text-primary-foreground">保存</button></div><div className="mt-4 space-y-2">{trends.map(t => <div key={t.id} className="rounded-lg bg-muted/50 p-3"><div className="flex justify-between text-sm"><strong>{t.title}</strong><span>{t.risk}</span></div><div className="mt-1 text-xs text-foreground/50">热度 {t.heat} · {t.source}</div></div>)}</div></section></div></div>
}
